name: faceblurring
channels:
  - defaults
dependencies:
  - python=3.8.12
  - black
  - colorama
  - isort
  - jupyterlab
  - numpy
  - opencv
  - tk
  - tqdm
  - scipy
  - pip
  - pip:
    - tensorflow-gpu==2.7.0
    - facenet-pytorch