name: faceblurring
channels:
  - defaults
dependencies:
  - python=3.10.11
  - black
  - colorama
  - Cython
  - isort
  - jupyterlab
  - numpy <1.24.0
  - tk
  - tqdm
  - scipy
  - pip
  - pip:
    - opencv-python
    - orjson==3.8.10
    - onnxruntime-gpu; sys_platform == 'linux'
    - onnxruntime-gpu; sys_platform == 'win32'
    - onnxruntime; sys_platform == 'darwin'
    - torch
    - insightface
    - nicegui